# WARN: Needs `ghcr.io/${{ github.repository_owner }}/makepkg:${{ github.sha }}` is ready by building.

name: Build PKGBUILD
description: Build PKGBUILD
inputs:
  makepkg-image:
    description: The docker image of makepkg
    required: false
    default: ghcr.io/${{ github.repository_owner }}/makepkg:${{ github.sha }}
  where:
    description: The directory contains PKGBUILD
    required: false
    default: ${{ github.workspace }}
  preserve-env:
    description: The comma seperated environment variables names
    required: false
  extra-makepkg-args:
    description: Extra arguments passed to makepkg
    required: false
runs:
  using: composite
  steps:
    - name: Prepare basic information
      id: prepare
      shell: bash
      run: |
        temp='${{ runner.temp }}'/"$(uuidgen)"
        mkdir -p "$temp"
        echo "temp=$temp" >> "$GITHUB_OUTPUT"

    - name: Copy startdir
      shell: bash
      run: |
        cp -a --no-preserve=ownership \
          '${{ inputs.where }}' '${{ steps.prepare.outputs.temp }}/startdir'

    - name: Copy srcdest
      shell: bash
      run: |
        if [[ -d srcdest ]]
        then
          cp -a --no-preserve=ownership \
            srcdest '${{ steps.prepare.outputs.temp }}'
        fi

    - name: Copy repository
      shell: bash
      run: |
        if [[ -d repo ]]
        then
          cp -a --no-preserve=ownership \
            repo '${{ steps.prepare.outputs.temp }}'
        fi

    - name: Run makepkg
      shell: bash
      run: |
        env | sudo docker run --workdir /startdir --rm \
          --env INPUT_PRESERVE_ENV='${{ inputs.preserve-env }}' \
          --env-file=/dev/stdin \
          --volume '${{ steps.prepare.outputs.temp }}/startdir:/startdir' \
          --volume '${{ steps.prepare.outputs.temp }}/pkgdest:/output/pkgdest' \
          --volume '${{ steps.prepare.outputs.temp }}/logdest:/output/logdest' \
          --volume '${{ steps.prepare.outputs.temp }}/srcdest:/input/srcdest' \
          --volume '${{ steps.prepare.outputs.temp }}/repo:/repo' \
          '${{ inputs.makepkg-image }}' ${{ inputs.extra-makepkg-args }} --log

    - name: Copy generated files
      shell: bash
      run: |
        sudo rm -rf srcdest pkgdest logdest
        cp -a --no-preserve=ownership -t . \
          '${{ steps.prepare.outputs.temp }}/srcdest' \
          '${{ steps.prepare.outputs.temp }}/pkgdest' \
          '${{ steps.prepare.outputs.temp }}/logdest'
        cp -a --no-preserve=ownership \
          '${{ steps.prepare.outputs.temp }}/startdir/PKGBUILD' \
          '${{ inputs.where }}'
