name: Get value in .SRCINFO
description: Query value in .SRCINFO

inputs:
  srcinfo:
    required: true
    description: The path to .SRCINFO
  key:
    required: true
    description: The key to query

outputs:
  value:
    description: The value in .SRCINFO
    value: ${{ steps.get-value.outputs.value }}

runs:
  using: composite
  steps:
    - name: Get value
      id: get-value
      run: |
        KEY="${{ inputs.key }}"
        SRCINFO="${{ inputs.srcinfo }}"
        EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
        echo "value<<$EOF" >> "$GITHUB_OUTPUT"
        grep "$KEY = " "$SRCINFO" | sed "s/$KEY = //;s/^\s*//"  >> "$GITHUB_OUTPUT" 
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
