name: Apply patches
description: Apply patches to pkgbase
inputs:
  where:
    description: The directory contains PKGBUILD
    required: true
  pkgbase:
    description: The pkgbase to apply
    required: true
  patches:
    description: Where is the directory contains patches for pkgbase
    required: false
    default: ${{ github.workspace }}/patches
runs:
  using: composite
  steps:
    - name: Apply patches
      working-directory: ${{ inputs.where }}
      shell: bash
      run: |
        if [[ -d '${{ inputs.patches }}/${{ inputs.pkgbase }}' ]]
        then
          shopt -s nullglob
          for f in '${{ inputs.patches }}/${{ inputs.pkgbase }}/'*.diff '${{ inputs.patches }}/${{ inputs.pkgbase }}/'*.patch
          do
            echo "Applying patch $f..."
            patch -Np1 -i "$f"
          done
        fi
