name: Generate environment mapping
description: Generate environment mapping from variable or secrets
inputs:
  env-names:
    description: Comma-seperated environment names
    required: true
outputs:
  env-mapping:
    description: The json mapping of generated environments
    value: ${{ steps.map.outputs.env-mapping }}
runs:
  using: composite
  steps:
    - name: Map environments
      shell: bash
      id: map
      run: |
        MAPS='{}'
        while read -r name
        do
          if [[ -n "$name" ]]
          then
            value="$(jq -r ".$name" <<< '${{ toJSON(vars) }}')"
            if [[ -z "$value" ]]
            then
              value="$(jq -r ".$name" <<< '${{ toJSON(secrets) }}')"
            fi
            if [[ -n "$value" ]]
            then
              MAPS="$(jq -r ".$name=\"$value\"" <<< "$MAPS")"
            fi
          fi
        done < <(sed "s/,/\n/g" <<< '${{ inputs.env-names }}')
        echo "env-mapping=$MAPS" >> "$GITHUB_OUTPUT"
