name: Update a pacman repository
description: Update or create a pacman repository
inputs:
  repo:
    description: The path to the repository
    required: true
  packages:
    description: The paths to packages
    required: false
    default: ''

runs:
  using: docker
  image: Dockerfile
  entrypoint: /update.sh
