name: Update a pacman repository
description: Update or create a pacman repository
inputs:
  path-to-repo:
    description: The path to the repository
    required: true
  packages:
    description: The paths to packages
    required: false
    default: ''

runs:
  using: docker
  image: docker://archlinux:base-devel
  args:
    - /usr/bin/repo-add
    - ${{ inputs.path-to-repo }}
    - ${{ inputs.packages }}
