name: Launch build container
description: Launch the container and start building
inputs:
  environment:
    description: The KEY=VALUE pair which used in makepkg
    required: false
    default: ''
  validpgpkeys:
    description: The GnuPG public keys file under workspace which is for builder to validate sources
    required: false
    default: ''

runs:
  using: docker
  image: Dockerfile
