# Modified from https://github.com/jlumbroso/free-disk-space
name: Clean Runner
description: Clean Runner to have more space for building.
runs:
  using: composite
  steps:
    - name: Clean Runner
      shell: bash
      run: |
        echo "Before cleanup:"
        sudo df -ah

        sudo rm -rf /usr/local/lib/android /usr/local/lib/node_modules \
                    /usr/local/graalvm \
                    /usr/local/julia \
                    /usr/local/share/powershell /usr/local/share/chromium \
                    /usr/share/dotnet \
                    /usr/share/swift \
                    /opt/ghc \
                    /opt/hostedtoolcache \
                    /usr/local/.ghcup \
                    /usr/lib/jvm

        sudo apt-get remove -y --fix-missing \
          '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' \
          azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri \
          google-cloud-sdk google-cloud-cli microsoft-edge-stable
        sudo apt-get autoremove -y
        sudo apt-get clean

        sudo docker image prune --force --filter=label!=com.github.actions.required=true
        sudo docker builder prune --force --all

        echo "After cleanup:"
        sudo df -ah
