name: Download packages artifacts
description: Download packages artifacts

inputs:
  directory:
    description: The directory to storage downloaded packages.
    required: true
  target-arch:
    description: The architecture of built packages.
    required: false

outputs:
  packages:
    description: Newline splitted string with packages names downloaded.
    value: ${{ steps.escape.outputs.packages }}

runs:
  using: composite
  steps:
    - name: Get target arch
      id: target-arch
      if: ${{ ! inputs.target-arch }}
      uses: ./.github/actions/get-target-arch

    - name: Create directory
      run: |
        mkdir -p "${{ inputs.directory }}"
      shell: bash

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.directory }}
        merge-multiple: true
        pattern: "* ${{ inputs.target-arch && inputs.target-arch || steps.target-arch.outputs.target-arch }}" 

    - name: Recover escaped files names
      id: escape
      run: |
        find "${{ inputs.directory }}" -maxdepth 1 -mindepth 1 -type f -name '*.pkg.tar.*.original.txt' | while read -r f
        do
          name="$(basename -s .original.txt "$f" )"
          original="$(< "$f")"
          echo "Recovering $original from $name..."
          mv "${{ inputs.directory }}/$name" "${{ inputs.directory }}/$original"
          rm "$f"
        done
        EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
        echo "packages<<$EOF" >> "$GITHUB_OUTPUT"
        find "${{ inputs.directory }}" -maxdepth 1 -mindepth 1 -type f -regex '.+\.pkg\.tar\.[a-zA-Z0-9]+$' -printf "%f\n" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
