name: Build PKGBUILD in container
description: Build Arch Linux PKGBUILD in container
inputs:
  repo:
    description: The git repository contains PKGBUILD
    required: true

  environment:
    description: The KEY=VALUE pair which used in makepkg
    required: false
    default: ''

  validpgpkeys:
    description: The GnuPG public keys file under workspace which is for builder to validate sources
    required: false
    default: 'gpg-key.asc'

outputs:
  artifact-name:
    description: The string which can be used as artifact name
    value: ${{ steps.gen-info.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Prepare environment
      id: gen-info
      uses: ./.github/actions/prepare-environment
      with:
        repo: ${{ inputs.repo }}
        validpgpkeys: ${{ inputs.validpgpkeys }}

    - name: Launch builder
      uses: ./.github/actions/launch-build-container
      with:
        environment: ${{ inputs.environment }}
        validpgpkeys: ${{ inputs.validpgpkeys }}
