name: Build PKGBUILD in container
description: Build Arch Linux PKGBUILD in container
inputs:
  repo:
    description: The git repository contains PKGBUILD
    required: true

  environment:
    description: The KEY=VALUE pair which used in makepkg
    required: false
    default: ''

  validpgpkeys:
    description: The GnuPG public keys file under workspace which is for builder to validate sources
    required: false
    default: 'gpg-key.asc'

  packages:
    description: The artifacts to the unofficial packages which is required to be installed
    required: false
    default: '' 

outputs:
  artifact-name:
    description: The string which can be used as artifact name
    value: ${{ steps.gen-info.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Prepare environment
      id: gen-info
      uses: ./.github/actions/prepare-environment
      with:
        repo: ${{ inputs.repo }}
        validpgpkeys: ${{ inputs.validpgpkeys }}
        packages: ${{ inputs.packages }}

    - name: Launch builder
      uses: ./.github/actions/launch-build-container
      with:
        environment: ${{ inputs.environment }}
        validpgpkeys: ${{ inputs.validpgpkeys }}

    - name: Ensure filename suitable for uploading
      run: |
        find pkgdest -maxdepth 1 -mindepth 1 -type f -name '*.pkg.tar.*' | while read -r f
        do
          name="$(basename "$f")"
          validname="$name"
          for char in '\:' '\"' '\<' '\>' '\|' '\*' '\?' "$(printf '\r')" "$(printf '\n')"
          do
            validname=${validname//$char/#}
          done
          if [[ "$name" != "$validname" ]]
          then 
            echo "Rewriting $name to $validname..."
            echo "$name" > "pkgdest/$validname.original.txt"
            mv "pkgdest/$name" "pkgdest/$validname"
          fi          
        done
      shell: bash
