name: Build PKGBUILD in container
description: Build Arch Linux PKGBUILD in container
inputs:
  pkgbuild-repo:
    description: The git repository contains PKGBUILD
    required: true

runs:
  using: composite
  steps:
    - name: Prepare environment
      uses: ./.github/actions/prepare-environment
      with:
        pkgbuild-repo: ${{ inputs.pkgbuild-repo }}

    - name: Launch builder
      uses: ./.github/actions/launch-build-container
