name: Prepare PKGBUILD
description: Prepare PKGBUILD for building
inputs:
  where:
    description: Where to get PKGBUILD
    required: true
  env:
    description: The KEY=VALUE lines exported when building
    required: false
  repo:
    description: The path to the repository contains dependencies not in official repositories
    required: false
outputs:
  artifact-name:
    description: The artifact name storage built package(s)
    value: ${{ steps.meta.outputs.artifact-name }}
runs:
  using: composite
  steps:
    - name: Obtain PKGBUILD
      shell: bash
      run: |
        where='${{ inputs.where }}'
        case "$where" in
          git+*)
            echo "Cloning repository with git..."
            git clone "${where#git+}" startdir
            ;;
          *)
            if [[ -d "$where" ]]
            then
              echo "Copying from local path..."
              cp -r "$where" startdir
            else
              echo "::error::Unsupported way to obtain PKGBUILD."
              exit 1
            fi
            ;;
        esac

    - name: Gen .SRCINFO
      uses: arenekosreal/makepkg-action@v0.2.3
      with:
        builddir: startdir
        args: --printsrcinfo
        stdout: startdir/.SRCINFO

    - name: Apply patch
      shell: bash
      run: |
        pkgbase="$(grep pkgbase startdir/.SRCINFO | cut -d = -f 2- | xargs)"
        if [[ -d "patches/$pkgbase" ]]
        then
          find "patches/$pkgbase" -maxdepth 1 -type f -name '*.patch' -o -name '*.diff' | \
          while read -r p
          do
            echo "Applying patch $p..."
            patch -Np1 -d startdir -i "../$p"
          done
        fi

    - name: Update .SRCINFO
      uses: arenekosreal/makepkg-action@v0.2.3
      with:
        builddir: startdir
        args: --printsrcinfo
        stdout: startdir/.SRCINFO

    - name: Fetch GPG fingerprints
      shell: bash
      run: |
        echo "GPG version:"
        gpg --version
        GPG=(gpg --batch --yes)
        KEYS_PGP="startdir/keys/pgp"
        mkdir -p "$KEYS_PGP"
        while read -r fingerprint
        do
          echo "Fetching $fingerprint..."
          FINGERPRINT_ASC="$KEYS_PGP/fingerprint.asc"
          if "${GPG[@]}" --recv-keys --keyserver keyserver.ubuntu.com "$fingerprint" && \
             "${GPG[@]}" --list-keys "$fingerprint"
          then
            echo "Fetch $fingerprint from keyserver.ubuntu.com successfully."
          elif "${GPG[@]}" --recv-keys --keyserver keys.openpgp.org "$fingerprint" && \
               "${GPG[@]}" --list-keys "$fingerprint"
          then
            echo "Fetch $fingerprint from keys.openpgp.org successfully."
          else
            echo "::error::Failed to fetch $fingerprint."
            exit 1
          fi
          echo "Exporting public key..."
          "${GPG[@]}" --export --armor -o "$FINGERPRINT_ASC" "$fingerprint"
        done < <(grep validpgpkeys startdir/.SRCINFO | cut -d = -f 2-)

    - name: Get pkgbase
      id: pkgbase
      run: |
        {
          echo -n value=
          grep pkgbase startdir/.SRCINFO | cut -d = -f 2- | xargs
        } >> "$GITHUB_OUTPUT"
      shell: bash
      
    - name: Get sources required downloading
      id: sources
      if: contains('["spotify"]', steps.pkgbase.outputs.value)
      run: |
        {
          EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
          echo "value<<$EOF"
          grep source startdir/.SRCINFO | cut -d = -f 2=
          echo "$EOF"
        } >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Download sources
      if: steps.sources.outputs.value
      shell: bash
      run: |
        mkdir -p srcdest
        # Permission maybe broen after docker action
        sudo chown -R --reference . srcdest
        while read -r source
        do
          case "$source" in
            *::http://*|*::https://*|*::ftp://*)
              read -r -a array <<< "${source//::/ }"
              name="${array[0]}"
              url=${array[1]}
              unset array
              ;;
            http://*|https://*|ftp://*)
              name="$(basename "$source")"
              url="$source"
              ;;
            *)
              echo "::warning::Unsupported source $source, skipping..."
              ;;
          esac
          if [[ -n "$name" ]] && [[ -n "$url" ]]
          then
            echo "Downloading $url to srcdest/$name..."
            wget --tries 0 --retry-connrefused --retry-on-host-error -O "srcdest/$name" "$url"
          fi
        done <<< '${{ steps.sources.outputs.value }}'

    - name: Bump pkgver
      if: endsWith(steps.pkgbase.outputs.value, '-git')
      uses: arenekosreal/makepkg-action@v0.2.3
      with:
        builddir: startdir
        env: ${{ inputs.env }}
        args: --nobuild
        updatepkgbuild: true
        repo: ${{ inputs.repo }}

    - name: Generate final .SRCINFO
      uses: arenekosreal/makepkg-action@v0.2.3
      with:
        builddir: startdir
        args: --printsrcinfo
        stdout: startdir/.SRCINFO

    - name: Generate meta info
      id: meta
      shell: bash
      run: |
        printf "artifact-name=%s %s-%d %s\n" \
          '${{ steps.pkgbase.outputs.value }}' \
          "$(grep pkgver startdir/.SRCINFO | cut -d = -f 2- | xargs)" \
          "$(grep pkgrel startdir/.SRCINFO | cut -d = -f 2- | xargs)" \
          "$(uname -m)" \
        >> "$GITHUB_OUTPUT"

    - name: Ensure pkgdest permission
      run: |
        mkdir -p pkgdest
        sudo chown -R --reference . pkgdest
      shell: bash

    - name: Try using packages built before
      id: cache
      uses: actions/cache@v4
      with:
        path: pkgdest
        key: ${{ steps.meta.outputs.artifact-name }}

    - name: Free space
      if: contains(fromJSON('["linux-pf", "ayugram-desktop"]'), steps.pkgbase.outputs.value) && ( steps.cache.outputs.cache-hit != 'true' ) && ! github.event.act.local
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        docker-images: false
        swap-storage: false

    - name: Check if requires --ignorearch
      id: needs-ignorearch
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        TARGET_ARCH="$(uname -m)"
        while read -r arch
        do
          if [[ "$arch" == "any" ]] || [[ "$arch" == "$TARGET_ARCH" ]]
          then
            echo result= >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done < <(grep arch startdir/.SRCINFO | cut -d = -f 2-)
        if [[ '${{ steps.pkgbase.outputs.value }}' == "spotify" ]] || [[ '${{ steps.pkgbase.outputs.value }}' == *-bin ]]
        then
          echo "::error::Unable to build binary package with --ignorearch"
          exit 1
        else
          echo "::warning:Current architecture is not supported by PKGBUILD, force building..."
          echo result=--ignorerch >> "$GITHUB_OUTPUT"
        fi

    - name: Build package
      if: steps.cache.outputs.cache-hit != 'true'
      uses: arenekosreal/makepkg-action@v0.2.3
      with:
        builddir: startdir
        env: ${{ inputs.env }}
        args: ${{ steps.needs-ignorearch.outputs.result }}
        repo: ${{ inputs.repo }}

    - name: Fix permission
      # https://github.com/actions/runner/issues/1282
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo chown -R --reference . pkgdest
