name: Create a new pacman repository
description: Create a new pacman repository
inputs:
  path-to-repo:
    description: The path to the repository
    required: true

runs:
  using: docker
  image: docker://archlinux:base-devel
  args: 
    - /usr/bin/repo-add 
    - ${{ inputs.path-to-repo }}
