name: Build makepkg
description: Build container image of makepkg
inputs:
  makepkg-image:
    description: The image tag
    required: false
    default: ghcr.io/${{ github.repository_owner }}/makepkg:${{ github.sha }}
  platforms:
    description: List of target platforms to build
    required: false
outputs:
  image-path:
    description: The path to exported image tarball file
    value: ${{ runner.temp }}/makepkg.tar.zst
  image-filename:
    description: The filename of exported image tarball
    value: makepkg.tar.zst
runs:
  using: composite
  steps:
    - name: Get native platform
      id: native-platform
      shell: bash
      run: echo "native-platform=$(sudo docker info --format '{{ .Host.OsArch }}')" >> "$GITHUB_OUTPUT"
      
    - name: Setup QEMU
      if: ${{ ! contains(fromJSON('["", "${{ steps.native-platform.outputs.native-platform }}"]'), inputs.platforms) }}
      uses: docker/setup-qemu-action@v3
  
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        tags: ${{ inputs.makepkg-image }}
        platforms: ${{ inputs.platforms }}
        outputs: type=docker,dest=${{ runner.temp }}/makepkg.tar.zst,compression=zstd
        context: ${{ github.action_path }}
