name: Download artifacts
description: Download artifacts with any filename
inputs:
  names:
    description: Newline-separated artifacts names
    required: false
  artifact-ids:
    description: Comma-separated artifacts ids
    required: false
  artifact-pattern:
    description: A glob pattern to the artifacts
    required: false
  path:
    description: Destination path
    required: false
    default: ${{ github.workspace }}
  github-token:
    description: The GitHub token used to authenticate with the GitHub API
    required: false
    default: ${{ github.token }}
  run-id:
    description: The id of the workflow run where the artifacts were uploaded from
    required: false
    default: ${{ github.run_id }}
outputs:
  download-path:
    description: Path of artifact download
    value: ${{ steps.download-artifact-by-id.outputs.download-path ||
               steps.download-artifact-by-pattern.outputs.download-path ||
               steps.download-artifact-by-name.outputs.download-path }}
runs:
  using: composite
  steps:
    - name: Download artifact by id
      id: download-artifact-by-id
      if: inputs.artifact-ids
      uses: actions/download-artifact@v5
      with:
        artifact-ids: ${{ inputs.artifact-ids }}
        path: ${{ inputs.path }}
        merge-multiple: true
        github-token: ${{ inputs.github-token }}
        run-id: ${{ inputs.run-id }}

    - name: Download artifact by pattern
      id: download-artifact-by-pattern
      if: inputs.artifact-pattern && ! inputs.artifact-ids
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        mkdir -p '${{ inputs.path }}'
        gh run download '${{ inputs.run-id }}' --dir '${{ inputs.path }}' --pattern '${{ inputs.artifact-pattern }}'
        find '${{ inputs.path }}' -mindepth 2 -type f -name "*.tar" \
          -exec cp -vt '${{ inputs.path }}' {} +
        find '${{ inputs.path }}' -mindepth 1 -maxdepth 1 -type d -exec rm -rfv {} +
        echo "download-path=$(realpath -m '${{ inputs.path }}')" >> "$GITHUB_OUTPUT"

    - name: Download artifact by name
      id: download-artifact-by-name
      if: inputs.names && ! inputs.artifact-ids && ! inputs.artifact-pattern
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        mkdir -p '${{ inputs.path }}'
        sed '/^[[:space:]]*$/d;s/^/-n /g' <<< '${{ inputs.names }}' | xargs \
          gh run download '${{ inputs.run-id }}' --dir '${{ inputs.path }}'
        echo "download-path=$(realpath -m '${{ inputs.path }}')" >> "$GITHUB_OUTPUT"

    - name: Unpack files
      shell: bash
      run: |
        find '${{ inputs.path }}' -type f -name '*.tar' \
          -printf "Extracting %f...\n" \
          -execdir tar -xvpf {} \; \
          -printf "Removing %f...\n" \
          -delete
