name: Prepare environment
description: Prepare environment for building PKGBUILDs
inputs:
  repo:
    description: The git repository contains PKGBUILD
    required: true
  validpgpkeys:
    description: Where to storage exported GnuPG key
    required: false
    default: gpg-key.asc
  packages:
    description: The artifacts to packages
    required: false
    default: ''
outputs:
  artifact-name:
    description: The string which can be used as artifact name
    value: ${{ steps.gen-output.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Prepare directories
      run: |
        rm -rf startdir pkgdest repo
        mkdir -p startdir pkgdest repo
      shell: bash
      
    - name: Download pkgbuild
      run: git clone ${{ inputs.repo }} startdir
      shell: bash

    - name: Download dependencies
      if: inputs.packages
      uses: actions/download-artifact@v4
      with:
        path: repo
        pattern: ${{ inputs.packages }}
        merge-multiple: true

    - name: Display filesystem status
      run: ls -lR .
      shell: bash

    - name: Generate pacman repository for building with dependency
      uses: ./.github/actions/update-pacman-repo
      with:
        repo: repo/repo.db.tar.gz

    - name: Generate output
      id: gen-output
      run: echo artifact-name=${{ inputs.repo }} | sed 's|=.*://|=|;s|.git$||;s|/| |g' >> $GITHUB_OUTPUT
      shell: bash

    - name: Scan GnuPG keys in PKGBUILD
      id: gpg-key
      uses: ./.github/actions/scan-gpg-keys
      with:
        directory: startdir

    - name: Obtain GnuPG keys
      if: steps.gpg-key.outputs.validpgpkeys
      run: |
        gpg --recv-keys ${{ steps.gpg-key.outputs.validpgpkeys }}
        if ! gpg --list-keys ${{ steps.gpg-key.outputs.validpgpkeys }}
        then 
          gpg --keyserver keyserver.ubuntu.com --recv-keys ${{ steps.gpg-key.outputs.validpgpkeys }}
          gpg --list-keys ${{ steps.gpg-key.outputs.validpgpkeys }}
        fi
      shell: bash

    - name: Export GnuPG keys
      if: steps.gpg-key.outputs.validpgpkeys
      run: gpg --export --armor -o ${{ inputs.validpgpkeys }} ${{ steps.gpg-key.outputs.validpgpkeys }}
      shell: bash
