name: Prepare environment
description: Prepare environment for building PKGBUILDs
inputs:
  pkgbuild-repo:
    description: The git repository contains PKGBUILD
    required: true
outputs:
  artifact-name:
    description: The string which can be used as artifact name
    value: ${{ steps.gen-output.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Prepare directories
      run: |
        rm -rf startdir pkgdest repo
        mkdir -p startdir pkgdest repo
      shell: bash
      
    - name: Download pkgbuild
      run: git clone ${{ inputs.pkgbuild-repo }} startdir
      shell: bash

    - name: Generate empty pacman repository for building with dependency
      uses: ./.github/actions/new-repo
      with:
        path-to-repo: repo/repo.db.tar.gz

    - name: Generate output
      id: gen-output
      run: echo artifact-name=${{ inputs.pkgbuild-repo }} | sed 's|=.*://|=|;s|.git$||' >> $GITHUB_OUTPUT
      shell: bash
