name: Build packages

on:
  schedule:
    - cron: 1 */8 * * *
  workflow_dispatch:   

jobs:
  simple-packages:
    name: Build packages which do not have any unofficial-repo dependency
    strategy:
      fail-fast: false
      matrix:
        pkgbuild-repo:
          - https://aur.archlinux.org/ares-decrypt.git
    runs-on: ubuntu-latest          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run builder
        uses: ./.github/actions/build-pkgbuild-in-container
        with:
          pkgbuild-repo: ${{ matrix.pkgbuild-repo }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgbuild-repo }}
          path: pkgdest/*.pkg.tar.*
          if-no-files-found: error
