name: Build package from git repository.
on:
  workflow_call:
    inputs:
      repository:
        required: true
        description: The repository of package.
        type: string
      runs-on:
        required: true
        description: The GitHub action runner.
        type: string
      env:
        required: false
        description: The env which will be passed to build action.
        type: string
      bump-pkgrel:
        required: false
        description: How many pkgrels are added to existing.
        type: number
        default: 0
    secrets:
      secret-env:
        description: env but supports secrets.*
        required: false
    outputs:
      artifact-name:
        description: The name of artifact which storage built package(s).
        value: ${{ jobs.build-single-package.outputs.artifact-name }}
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: The repository of package.
        type: string
      runs-on:
        required: true
        description: The GitHub action runner.
        type: string
      env:
        required: false
        description: The env which will be passed to build action.
        type: string
      bump-pkgrel:
        required: false
        description: How many pkgrels are added to existing.
        type: number
        default: 0
jobs:
  build-single-package:
    name: Build ${{ inputs.repository }}
    runs-on: ${{ inputs.runs-on }}
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout PKGBUILD
        run: |
          git clone "${{ inputs.repository }}" startdir
      - name: Start building
        id: build
        uses: ./.github/actions/build-pkgbuild
        with:
          builddir: startdir
          env: |
            PACKAGER=${{ vars.PACKAGER }}
            ${{ inputs.env }}
            ${{ github.event_name == 'workflow_call' && inputs.secret-env || '' }}
          bump-pkgrel: ${{ inputs.bump-pkgrel }}
