on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  generate-repo:
    if: github.event.release.draft || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Generate pacman repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download release
        id: download-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tagName="$(gh release list --exclude-pre-releases --jq '.[] | select(.isDraft) | .tagName' --limit 1 --json tagName,isDraft)"
          rm -rf repo
          gh release download "$tagName" --dir repo
          echo tag_name="$tagName" >> "$GITHUB_OUTPUT"

      - name: Generate repository
        uses: ./.github/actions/update-pacman-repo
        with:
          repo: repo

      - name: Update release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ steps.download-release.outputs.tag_name }}" \
            *.db \
            *.db.tar.* \
            *.files \
            *.files.tar.* \
            --clobber
          gh release edit "${{ steps.download-release.outputs.tag_name }}" \
            --draft=false
