on:
  release:
    types:
      - published
  workflow_dispatch:

name: Generate Repo

jobs:
  generate-repo:
    if: github.event.release.draft || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Generate pacman repository
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download release
        id: download-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list
          tagName="$(gh release list --exclude-pre-releases --jq '.[] | select(.isDraft) | .tagName' --limit 1 --json tagName,isDraft)"
          echo "Found release tag $tagName"
          rm -rf "$tagName"
          gh release download "$tagName" --dir "$tagName"
          echo "Downloaded release tag $tagName"
          echo tag_name="$tagName" >> "$GITHUB_OUTPUT"

      - name: Generate repository
        uses: ./.github/actions/update-pacman-repo
        with:
          repo: repo/repo.db.tar.gz

      - name: Update release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ steps.download-release.outputs.tag_name }}" \
            repo/repo.db.tar.gz \
            repo/repo.files.tar.gz
          gh release edit "${{ steps.download-release.outputs.tag_name }}" \
            --draft=false
