name: Download sources in PKGBUILD
description: Download sources in PKGBUILD
inputs:
  directory:
    description: The path to directory contains PKGBUILD
    required: true

runs:
  using: docker
  image: Dockerfile
  entrypoint: /download.sh
